name: e_flag_down
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+4
  tflite_flutter: ^0.10.1
  image: ^3.0.1
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

uses-material-design: true
